In [7]:
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1, as_frame=False)

In [15]:
X_train, y_train = mnist["data"], mnist["target"]
X_train.shape

(70000, 784)

In [16]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
y_train

array(['5', '0', '4', ..., '4', '5', '6'], dtype=object)

In [18]:
# SGDCLassifier 훈련시키기
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(max_iter=5, tol=-np.infty, random_state = 42)
sgd_clf.fit(X_train, y_train)

SGDClassifier(max_iter=5, random_state=42, tol=-inf)

In [19]:
# 10-fold 교차 검증
from sklearn.model_selection import cross_val_score
cross_val_score(sgd_clf, X_train, y_train, cv=10, scoring="accuracy")

array([0.87228571, 0.87757143, 0.87942857, 0.874     , 0.882     ,
       0.87785714, 0.86885714, 0.852     , 0.86528571, 0.88714286])

In [20]:
np.mean([0.87228571, 0.87757143, 0.87942857, 0.874     , 0.882     ,
       0.87785714, 0.86885714, 0.852     , 0.86528571, 0.88714286])

0.873642856

In [34]:
# USING RANDOM FOREST

In [23]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)

In [24]:
rf_clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [25]:
from sklearn.model_selection import cross_val_score
cross_val_score(rf_clf, X_train, y_train, cv=10, scoring="accuracy")

array([0.97185714, 0.96685714, 0.96985714, 0.96928571, 0.96571429,
       0.96971429, 0.96485714, 0.96928571, 0.97085714, 0.97642857])

In [26]:
np.mean([0.97185714, 0.96685714, 0.96985714, 0.96928571, 0.96571429,
       0.96971429, 0.96485714, 0.96928571, 0.97085714, 0.97642857])  # n_estimantors=100 -> 0.969

0.9694714269999999

In [27]:
from sklearn.ensemble import RandomForestClassifier
rf_clf_2 = RandomForestClassifier(n_estimators=200, random_state=42)
rf_clf_2.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [28]:
from sklearn.model_selection import cross_val_score
cross_val_score(rf_clf_2, X_train, y_train, cv=10, scoring="accuracy")

array([0.97414286, 0.96757143, 0.971     , 0.96871429, 0.96757143,
       0.971     , 0.96528571, 0.97014286, 0.971     , 0.97642857])

In [29]:
np.mean([0.97414286, 0.96757143, 0.971     , 0.96871429, 0.96757143,
       0.971     , 0.96528571, 0.97014286, 0.971     , 0.97642857])  #n_estimators=200 -> 0.970

0.9702857149999999

In [33]:
from sklearn.model_selection import GridSearchCV

params = { 'n_estimators': [500, 1000], 
            'max_depth': [None, 10, 15, 20, 30], 
            'min_samples_leaf': [10, 15, 20],
            'min_samples_split': [10, 20, 30]}
rf_clf_3 = RandomForestClassifier(random_state = 0, n_jobs = -1)
grid_cv = GridSearchCV(rf_clf_3, param_grid=params, cv=3, n_jobs=-1) #cv 수정 필요.
grid_cv.fit(X_train, y_train)
print('최적 하이퍼 파라미터: ', grid_cv.best_params_)
print('최고 예측 정확도: {:.4f}'.format(grid_cv.best_score_))

최적 하이퍼 파라미터:  {'max_depth': None, 'min_samples_leaf': 10, 'min_samples_split': 10, 'n_estimators': 500}
최고 예측 정확도: 0.9553


In [37]:
rf_clf_3_2 = RandomForestClassifier(n_estimators = 200,
                                 random_state = 42,
                                 n_jobs = -1)
rf_clf_3_2.fit(X_train, y_train)
cross_val_score(rf_clf_3_2, X_train, y_train, cv=10, scoring="accuracy")

array([0.97414286, 0.96757143, 0.971     , 0.96871429, 0.96757143,
       0.971     , 0.96528571, 0.97014286, 0.971     , 0.97642857])

In [38]:
np.mean([0.97414286, 0.96757143, 0.971     , 0.96871429, 0.96757143,
       0.971     , 0.96528571, 0.97014286, 0.971     , 0.97642857])

0.9702857149999999