In [2]:
import numpy as np
import pandas as pd

input_file = "train.csv"
# df_train = pd.read_csv(input_file, header = None)
df_train = pd.read_csv(input_file)

In [3]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7352 entries, 0 to 7351
Columns: 563 entries, tBodyAcc-mean()-X to Activity
dtypes: float64(561), int64(1), object(1)
memory usage: 31.6+ MB


In [4]:
type(df_train)

pandas.core.frame.DataFrame

In [3]:
active_state = df_train["Activity"]
active_state

0               STANDING
1               STANDING
2               STANDING
3               STANDING
4               STANDING
              ...       
7347    WALKING_UPSTAIRS
7348    WALKING_UPSTAIRS
7349    WALKING_UPSTAIRS
7350    WALKING_UPSTAIRS
7351    WALKING_UPSTAIRS
Name: Activity, Length: 7352, dtype: object

In [4]:
data_train = df_train.to_numpy()
data_train

array([[0.28858451, -0.020294171, -0.13290514, ..., -0.058626924, 1,
        'STANDING'],
       [0.27841883, -0.016410568, -0.12352019, ..., -0.054316717, 1,
        'STANDING'],
       [0.27965306, -0.019467156, -0.11346169, ..., -0.049117815, 1,
        'STANDING'],
       ...,
       [0.27338737, -0.017010616, -0.045021828, ..., 0.040811188, 30,
        'WALKING_UPSTAIRS'],
       [0.28965416, -0.018843044, -0.15828059, ..., 0.025339478, 30,
        'WALKING_UPSTAIRS'],
       [0.35150347, -0.012423118, -0.20386717, ..., 0.036694843, 30,
        'WALKING_UPSTAIRS']], dtype=object)

In [5]:
data_train.shape

(7352, 563)

### data_train[0:, -1:]은 7351개 열. data_train[0:,-1]은 1개 열

In [6]:
y_train = data_train[:, -1]  # y_train: 라벨 값
# data_train[:, -1] 수정 전

In [7]:
y_train

array(['STANDING', 'STANDING', 'STANDING', ..., 'WALKING_UPSTAIRS',
       'WALKING_UPSTAIRS', 'WALKING_UPSTAIRS'], dtype=object)

In [8]:
X_train = data_train[:, :-2]  # 각 특성의 값

In [9]:
X_train

array([[0.28858451, -0.020294171, -0.13290514, ..., -0.84124676,
        0.17994061, -0.058626924],
       [0.27841883, -0.016410568, -0.12352019, ..., -0.8447876,
        0.18028889, -0.054316717],
       [0.27965306, -0.019467156, -0.11346169, ..., -0.84893347,
        0.18063731, -0.049117815],
       ...,
       [0.27338737, -0.017010616, -0.045021828, ..., -0.77913261,
        0.24914484, 0.040811188],
       [0.28965416, -0.018843044, -0.15828059, ..., -0.78518142,
        0.24643223, 0.025339478],
       [0.35150347, -0.012423118, -0.20386717, ..., -0.78326693,
        0.24680852, 0.036694843]], dtype=object)

In [227]:
X_train.shape

(7352, 561)

## 특성 이름 리스트

## X_train (7352, 561), y_train (7352, 1), feature_names (1, 561)

In [112]:
feature_names = data_train[:1, :-2]  # 특성 이름 리스트, subject와 Activities는 제외
feature_names.shape

(1, 561)

# Test Set

In [243]:
test_file = "test.csv"
df_test = pd.read_csv(test_file)
# data_test = df_test.to_numpy()
# data_test
data_test = df_test.to_numpy()
data_test.shape

(2947, 563)

In [244]:
data_test

array([[0.25717778, -0.02328523, -0.014653762, ..., -0.057978304, 2,
        'STANDING'],
       [0.28602671, -0.013163359, -0.11908252, ..., -0.083898014, 2,
        'STANDING'],
       [0.27548482, -0.02605042, -0.11815167, ..., -0.079346197, 2,
        'STANDING'],
       ...,
       [0.34996609, 0.030077442, -0.11578796, ..., 0.18118355, 24,
        'WALKING_UPSTAIRS'],
       [0.23759383, 0.01846687, -0.096498932, ..., 0.18756291, 24,
        'WALKING_UPSTAIRS'],
       [0.15362719, -0.018436506, -0.13701846, ..., 0.1881034, 24,
        'WALKING_UPSTAIRS']], dtype=object)

In [245]:
# y_test = data_test[:, -1]
# y_test
X_test = data_test[:, :-2]
X_test

array([[0.25717778, -0.02328523, -0.014653762, ..., -0.72000927,
        0.27680104, -0.057978304],
       [0.28602671, -0.013163359, -0.11908252, ..., -0.69809082,
        0.28134292, -0.083898014],
       [0.27548482, -0.02605042, -0.11815167, ..., -0.70277146,
        0.28008303, -0.079346197],
       ...,
       [0.34996609, 0.030077442, -0.11578796, ..., -0.65535684,
        0.27447878, 0.18118355],
       [0.23759383, 0.01846687, -0.096498932, ..., -0.65971859,
        0.26478161, 0.18756291],
       [0.15362719, -0.018436506, -0.13701846, ..., -0.66008023,
        0.26393619, 0.1881034]], dtype=object)

In [247]:
y_test = data_test[:, -1:]
y_test

array([['STANDING'],
       ['STANDING'],
       ['STANDING'],
       ...,
       ['WALKING_UPSTAIRS'],
       ['WALKING_UPSTAIRS'],
       ['WALKING_UPSTAIRS']], dtype=object)

# 훈련 시작

## 결정 트리

In [114]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(max_depth=5, random_state=42)
tree_clf.fit(X_train, y_train)
y_test = data_test[1:, -1:]

## 선형 회귀

In [91]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(solver="liblinear", random_state=42)
log_reg.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(random_state=42, solver='liblinear')

## 앙상블

In [92]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes = 16, n_jobs = -1, random_state = 42)
rnd_clf.fit(X_train, y_train)
y_pred_rf = rnd_clf.predict(X_test)
y_pred_rf

<ipython-input-92-a93ad58cdc6a>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rnd_clf.fit(X_train, y_train)


array(['STANDING', 'STANDING', 'STANDING', ..., 'WALKING_UPSTAIRS',
       'WALKING_UPSTAIRS', 'WALKING'], dtype=object)

In [93]:
# y_test 와 y_pred_rf 와 비교를 해야하는데
# y_test.ravel()
y_test = y_test.ravel()
y_test

array(['STANDING', 'STANDING', 'STANDING', ..., 'WALKING_UPSTAIRS',
       'WALKING_UPSTAIRS', 'WALKING_UPSTAIRS'], dtype=object)

In [94]:
y_pred_rf.shape

(2947,)

In [86]:
np.sum(y_pred_rf == y_test) / len(y_test)

0.94069640914037

## Data Setting

In [210]:
y_train.ravel()
y_train

array(['LAYING', 'LAYING', 'LAYING', ..., 'WALKING_UPSTAIRS',
       'WALKING_UPSTAIRS', 'WALKING_UPSTAIRS'], dtype=object)

## 특성 중요도 확인... 의미있냐?

In [116]:
from sklearn.ensemble import RandomForestClassifier

rnd_clf = RandomForestClassifier(n_estimators=500, n_jobs=-1, random_state=42)
# rnd_clf.fit(X_train, y_train)
rnd_clf.fit(X_train, y_train.ravel())
sum = 0
feature_score = {}
for name, score in zip(feature_names.ravel(), rnd_clf.feature_importances_):
    print(name, score)
    feature_score[name]=score

tBodyAcc-mean()-X 0.0002116181367236854
tBodyAcc-mean()-Y 0.00026652714713865084
tBodyAcc-mean()-Z 0.00018164883281189992
tBodyAcc-std()-X 0.003891625985172786
tBodyAcc-std()-Y 0.000429236433781986
tBodyAcc-std()-Z 0.0005709161299481478
tBodyAcc-mad()-X 0.003167016749640834
tBodyAcc-mad()-Y 0.0005269458719602301
tBodyAcc-mad()-Z 0.00033923896496478934
tBodyAcc-max()-X 0.007024376590806755
tBodyAcc-max()-Y 0.0002863657189465549
tBodyAcc-max()-Z 0.00021735456800469298
tBodyAcc-min()-X 0.0004409407939287007
tBodyAcc-min()-Y 0.00022705956673790392
tBodyAcc-min()-Z 0.00021906863164008453
tBodyAcc-sma() 0.0007590182900184861
tBodyAcc-energy()-X 0.00511978423544547
tBodyAcc-energy()-Y 0.0005655413738821454
tBodyAcc-energy()-Z 0.0004296303266917228
tBodyAcc-iqr()-X 0.0010929280062631859
tBodyAcc-iqr()-Y 0.00048395244180100757
tBodyAcc-iqr()-Z 0.00019584096438820666
tBodyAcc-entropy()-X 0.0013498318070793128
tBodyAcc-entropy()-Y 0.00024580290718435795
tBodyAcc-entropy()-Z 0.0003048920516665027


In [117]:
import operator
score_import = sorted(feature_score.items(), key=lambda item: item[1])  # 특성 중요도 오름 차순 정렬

In [118]:
score_import

[('fBodyBodyAccJerkMag-entropy()', 9.124133374211118e-05),
 ('fBodyBodyAccJerkMag-min()', 0.00010967152744543948),
 ('fBodyAccJerk-min()-X', 0.00011157941115907988),
 ('fBodyAccJerk-min()-Z', 0.00011322431192383751),
 ('fBodyAccJerk-bandsEnergy()-57,64', 0.00012335761249464514),
 ('tBodyAccJerk-mean()-Y', 0.00012454734972521192),
 ('fBodyAccJerk-min()-Y', 0.00012604330381819394),
 ('fBodyAcc-bandsEnergy()-49,64', 0.00012679305281203973),
 ('fBodyBodyGyroJerkMag-entropy()', 0.00012718616004176017),
 ('fBodyAcc-bandsEnergy()-57,64', 0.00013014894599606944),
 ('fBodyAcc-min()-Y', 0.0001312190882594536),
 ('angle(tBodyAccJerkMean),gravityMean)', 0.0001322387459512298),
 ('fBodyAcc-min()-Z', 0.00013316159961686606),
 ('tBodyGyroJerk-mean()-Y', 0.00013657166615207677),
 ('fBodyAcc-maxInds-Z', 0.00013843928822626013),
 ('fBodyAccMag-min()', 0.00013864719334706242),
 ('fBodyBodyGyroJerkMag-min()', 0.00013938540870496243),
 ('tBodyAccJerk-arCoeff()-X,2', 0.00013980371696932118),
 ('angle(tBodyA

In [119]:
feature_top_10 = score_import[-10:]  # 특성 중요도 상위 10개만 추출
feature_top_10

[('tGravityAcc-energy()-Y', 0.01579407636810581),
 ('tGravityAcc-min()-Y', 0.02339897976119482),
 ('tGravityAcc-max()-X', 0.02341361680182947),
 ('tGravityAcc-energy()-X', 0.024597253647712834),
 ('tGravityAcc-max()-Y', 0.02468428544436485),
 ('angle(Y,gravityMean)', 0.024800831341755338),
 ('tGravityAcc-mean()-Y', 0.027619027418676764),
 ('angle(X,gravityMean)', 0.029082822887639942),
 ('tGravityAcc-mean()-X', 0.03191646425636396),
 ('tGravityAcc-min()-X', 0.03295574359144732)]

# 5주차 10p. 오차행렬

## sgd_clf 사용

In [233]:
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(max_iter=5, tol=-np.infty, random_state=42)
sgd_clf.fit(X_train, y_train)
cross_val_score(sgd_clf, X_train, y_train, cv=10, scoring="accuracy")

array([0.97826087, 0.85733696, 0.94693878, 0.80680272, 0.90884354,
       0.91020408, 0.97142857, 0.91020408, 0.95646259, 0.94693878])

In [234]:
y_train_pred = cross_val_predict(sgd_clf, X_train, y_train, cv=10)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, y_train_pred)

array([[1402,    2,    2,    0,    1,    0],
       [  12, 1109,  165,    0,    0,    0],
       [   0,  130, 1244,    0,    0,    0],
       [   0,    2,    1, 1132,   20,   71],
       [   0,    0,    0,   18,  879,   89],
       [   0,   11,    0,   38,   31,  993]], dtype=int64)

In [235]:
y_train_perfect_predictions = y_train
confusion_matrix(y_train, y_train_perfect_predictions)

array([[1407,    0,    0,    0,    0,    0],
       [   0, 1286,    0,    0,    0,    0],
       [   0,    0, 1374,    0,    0,    0],
       [   0,    0,    0, 1226,    0,    0],
       [   0,    0,    0,    0,  986,    0],
       [   0,    0,    0,    0,    0, 1073]], dtype=int64)

# 행렬 섞기 using random.permutation

In [15]:
random_matrix = np.random.permutation(7352)
X_train, y_train = X_train[random_matrix], y_train[random_matrix]

In [19]:
df_train.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.923527         -0.934724  ...                        -0.710304   
1         -0.957686         -0.943068  ...                        -0.861499   
2         -0.977469         -0.938692  ...                        -0.760104   
3         -0.989302         -0.938692  ...                        -0.482845   
4         -0.990441         -0.942469  ...                        -0.699205   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.112754                              0.030400   
1                     0.053477                             -0.007435   
2                    -0.118559                              0.177899   
3                    -0.036788                             -0.012892   
4                     0.123320                              0.122542   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.464761                             -0.018446   
1                         -0.732626                              0.703511   
2                          0.100699                              0.808529   
3                          0.640011                             -0.485366   
4                          0.693578                             -0.615971   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  subject  \
0             -0.841247              0.179941             -0.058627        1   
1             -0.844788              0.180289             -0.054317        1   
2             -0.848933              0.180637             -0.049118        1   
3             -0.848649              0.181935             -0.047663        1   
4             -0.847865              0.185151             -0.043892        1   

   Activity  
0  STANDING  
1  STANDING  
2  STANDING  
3  STANDING  
4  STANDING  

[5 rows x 563 columns]

In [49]:
train_new = df_train
train_new = train_new.to_numpy()
train_new = np.random.permutation(train_new)
train_new = train_new[10:15]
train_new

array([[0.27808522, -0.016763951, -0.10948183, ..., -0.28060117, 15,
        'LAYING'],
       [0.31802397, -0.052695467, -0.10073269, ..., -0.20246674, 25,
        'WALKING_DOWNSTAIRS'],
       [0.2866066, 0.003880909, -0.087586916, ..., 0.36803801, 14,
        'WALKING_UPSTAIRS'],
       [0.1813668, -0.046876094, -0.085992775, ..., 0.33031835, 17,
        'WALKING_UPSTAIRS'],
       [0.27308245, -0.025258983, -0.097738165, ..., -0.16921216, 30,
        'SITTING']], dtype=object)

In [64]:
X_train_new = train_new[:, :-2]
X_train_new
y_train_new = train_new[:, -1]
y_train_new

array(['LAYING', 'WALKING_DOWNSTAIRS', 'WALKING_UPSTAIRS',
       'WALKING_UPSTAIRS', 'SITTING'], dtype=object)

In [65]:
random_matrix_new = np.random.permutation(5)
X_train_new_new, y_train_new_new = X_train_new[random_matrix_new], y_train_new[random_matrix_new]

In [66]:
X_train_new_new

array([[0.2866066, 0.003880909, -0.087586916, ..., -0.40471506,
        0.31590057, 0.36803801],
       [0.1813668, -0.046876094, -0.085992775, ..., -0.52018007,
        0.23119257, 0.33031835],
       [0.27308245, -0.025258983, -0.097738165, ..., -0.74104961,
        0.079120214, -0.16921216],
       [0.27808522, -0.016763951, -0.10948183, ..., 0.45083316,
        -0.69983334, -0.28060117],
       [0.31802397, -0.052695467, -0.10073269, ..., -0.69249915,
        0.12715487, -0.20246674]], dtype=object)

In [67]:
y_train_new_new

array(['WALKING_UPSTAIRS', 'WALKING_UPSTAIRS', 'SITTING', 'LAYING',
       'WALKING_DOWNSTAIRS'], dtype=object)

## RandomForestClassifier

In [320]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes = 16, n_jobs = -1, random_state = 42)
rnd_clf.fit(X_train, y_train)
cross_val_score(rnd_clf, X_train, y_train, cv=10, scoring="accuracy")

array([0.92798913, 0.94293478, 0.93469388, 0.92517007, 0.92517007,
       0.94013605, 0.94421769, 0.93469388, 0.93061224, 0.93741497])

In [321]:
np.mean([0.93070652, 0.95108696, 0.93469388, 0.91156463, 0.93061224,
       0.93469388, 0.93197279, 0.9414966 , 0.9292517 , 0.93877551])  # 랜덤 포레스트 평균 0.933

0.9334854709999998

In [259]:
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import SGDClassifier


sgd_clf = SGDClassifier(max_iter=5, tol=-np.infty, random_state=42)
sgd_clf.fit(X_train, y_train)
cross_val_score(sgd_clf, X_train, y_train, cv=10, scoring="accuracy")

array([0.9701087 , 0.95380435, 0.96326531, 0.95646259, 0.94693878,
       0.93061224, 0.96462585, 0.97414966, 0.95510204, 0.97278912])

In [260]:
np.mean([0.9701087 , 0.95380435, 0.96326531, 0.95646259, 0.94693878,
       0.93061224, 0.96462585, 0.97414966, 0.95510204, 0.97278912])  # SGD 평균: 0.959

0.958785864

# Use Bagging

In [280]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier


log_clf = LogisticRegression(solver="liblinear", C=10, random_state=42)
rnd_clf = RandomForestClassifier(n_estimators=100, random_state=42)
svm_clf = SVC(gamma="auto", probability=True, random_state=42)
sgd_clf = SGDClassifier(max_iter=5, tol=-np.infty, random_state=42)

voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf), ('sgd', sgd_clf)],
    voting='hard'
)
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(random_state=42,
                                                 solver='liblinear')),
                             ('rf', RandomForestClassifier(random_state=42)),
                             ('svc',
                              SVC(gamma='auto', probability=True,
                                  random_state=42)),
                             ('sgd',
                              SGDClassifier(max_iter=5, random_state=42,
                                            tol=-inf))])

In [281]:
from sklearn.metrics import accuracy_score
for clf in (log_clf, rnd_clf, svm_clf, sgd_clf, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.9619952494061758
RandomForestClassifier 0.9273837801153716
SVC 0.9402782490668476
SGDClassifier 0.9379029521547336
VotingClassifier 0.9487614523243977


In [283]:
cross_val_score(voting_clf, X_train, y_train, cv=10, scoring="accuracy")

array([0.98097826, 0.98369565, 0.96870748, 0.97687075, 0.97823129,
       0.98503401, 0.98503401, 0.97687075, 0.9755102 , 0.98639456])

In [ ]:
cross_val_score(voting_clf, X_train, y_train, cv=10, scoring="accuracy")

In [284]:
np.mean([0.98097826, 0.98369565, 0.96870748, 0.97687075, 0.97823129,
       0.98503401, 0.98503401, 0.97687075, 0.9755102 , 0.98639456])

0.9797326960000001

# Logistic Regression 사용


### solver="lbfgs" && multi_class="multinomial", max_iter 값 작게 주면 에러

In [308]:
softmax_reg = LogisticRegression(max_iter=5000, multi_class="multinomial", solver="lbfgs", C=10, random_state=42)
softmax_reg.fit(X_train ,y_train)
cross_val_score(softmax_reg, X_train, y_train, cv=10, scoring="accuracy")

array([0.99048913, 0.98641304, 0.97959184, 0.98639456, 0.98911565,
       0.99591837, 0.98639456, 0.97959184, 0.99047619, 0.98231293])

In [309]:
np.mean([0.99048913, 0.98641304, 0.97959184, 0.98639456, 0.98911565,
       0.99591837, 0.98639456, 0.97959184, 0.99047619, 0.98231293])

0.9866698110000002

## solver="liblinear"사용

In [316]:
log_clf_2 = LogisticRegression(solver="liblinear", C=10, random_state=42)
log_clf_2.fit(X_train, y_train)
cross_val_score(log_clf_2, X_train, y_train, cv=10, scoring="accuracy")

array([0.98913043, 0.98777174, 0.98095238, 0.98503401, 0.99047619,
       0.99455782, 0.9877551 , 0.98095238, 0.9877551 , 0.98367347])

### 최최종!!! LogisticRegression!!

In [317]:
np.mean([0.98913043, 0.98777174, 0.98095238, 0.98503401, 0.99047619,
       0.99455782, 0.9877551 , 0.98095238, 0.9877551 , 0.98367347])

0.986805862

In [318]:
y_train_pred = cross_val_predict(log_clf_2, X_train, y_train, cv=10)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, y_train_pred)

array([[1407,    0,    0,    0,    0,    0],
       [   0, 1240,   45,    0,    0,    1],
       [   0,   49, 1325,    0,    0,    0],
       [   0,    0,    0, 1225,    0,    1],
       [   0,    0,    0,    0,  986,    0],
       [   0,    0,    0,    1,    0, 1072]], dtype=int64)

# AdaBoost 사용 해보자


In [327]:
from sklearn.ensemble import AdaBoostClassifier
ada_clf = AdaBoostClassifier(
    RandomForestClassifier(n_jobs = -1, random_state = 42),
    algorithm="SAMME.R", learning_rate=0.01, random_state=42)
ada_clf.fit(X_train, y_train)

AdaBoostClassifier(base_estimator=RandomForestClassifier(n_jobs=-1,
                                                         random_state=42),
                   learning_rate=0.01, random_state=42)

In [328]:
cross_val_score(ada_clf, X_train, y_train, cv=10, scoring="accuracy")  # 버려 0.8나옴

array([0.98097826, 0.98233696, 0.98639456, 0.97687075, 0.97142857,
       0.98639456, 0.98095238, 0.97823129, 0.97959184, 0.98503401])

In [329]:
np.mean([0.98097826, 0.98233696, 0.98639456, 0.97687075, 0.97142857,
       0.98639456, 0.98095238, 0.97823129, 0.97959184, 0.98503401])

0.9808213179999999

## Random Forest 2트

In [322]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_jobs = -1, random_state = 42)
rnd_clf.fit(X_train, y_train)
cross_val_score(rnd_clf, X_train, y_train, cv=10, scoring="accuracy")

array([0.97961957, 0.98097826, 0.99183673, 0.97959184, 0.97687075,
       0.98503401, 0.98231293, 0.98639456, 0.9877551 , 0.98231293])

In [323]:
np.mean([0.97961957, 0.98097826, 0.99183673, 0.97959184, 0.97687075,
       0.98503401, 0.98231293, 0.98639456, 0.9877551 , 0.98231293])

0.9832706679999997

## Using Gradient Boosting이 가장 좋은 결과

In [331]:
from sklearn.ensemble import GradientBoostingClassifier
gbrt = GradientBoostingClassifier(random_state=42)  
gbrt.fit(X_train, y_train)
cross_val_score(gbrt, X_train, y_train, cv=10, scoring="accuracy")

array([0.99048913, 0.99184783, 0.99183673, 0.98503401, 0.99183673,
       0.9877551 , 0.98639456, 0.98503401, 0.99455782, 0.9877551 ])

In [332]:
np.mean([0.99048913, 0.99184783, 0.99183673, 0.98503401, 0.99183673,
       0.9877551 , 0.98639456, 0.98503401, 0.99455782, 0.9877551 ])

0.989254102

## GradientBoosting 오차행렬 결과

In [333]:
from sklearn.metrics import confusion_matrix
y_train_pred = cross_val_predict(gbrt, X_train, y_train, cv=10)
confusion_matrix(y_train, y_train_pred)

array([[1406,    0,    0,    0,    1,    0],
       [   0, 1249,   36,    0,    0,    1],
       [   0,   30, 1344,    0,    0,    0],
       [   0,    0,    0, 1219,    3,    4],
       [   0,    0,    0,    1,  983,    2],
       [   0,    0,    0,    1,    0, 1072]], dtype=int64)

# 99%를 위한 노력. GridSearchCV

In [334]:
from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators': [100, 500, 100],
    'learning_rate': [0.05, 0.1, 0.5],
    'max_depth': [3, 5, 8]
}

gb_grid = GridSearchCV(gbrt, param_grid = params, cv=3, verbose = 1, n_jobs=-1)

In [ ]:
cross_val_score(gb_grid, X_train, y_train, cv=10, scoring="accuracy")

Fitting 3 folds for each of 27 candidates, totalling 81 fits


In [ ]:
gb_grid.fit(X_train, y_train)
print("최적 하이퍼 파라미터", gb_grid.best_params_)
print("최고의 예측 정확도:", gb_grid.best_score_)