# Human Activity Recognition (HAR) -20171539 최대한

**pandas의 read_csv로 'train.csv' 파일을 df_train에 읽기**

In [217]:
import numpy as np
import pandas as pd

input_file = "train.csv"
df_train = pd.read_csv(input_file)

In [218]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7352 entries, 0 to 7351
Columns: 563 entries, tBodyAcc-mean()-X to Activity
dtypes: float64(561), int64(1), object(1)
memory usage: 31.6+ MB


In [220]:
data_train = df_train.to_numpy()
data_train

array([[0.28858451, -0.020294171, -0.13290514, ..., -0.058626924, 1,
        'STANDING'],
       [0.27841883, -0.016410568, -0.12352019, ..., -0.054316717, 1,
        'STANDING'],
       [0.27965306, -0.019467156, -0.11346169, ..., -0.049117815, 1,
        'STANDING'],
       ...,
       [0.27338737, -0.017010616, -0.045021828, ..., 0.040811188, 30,
        'WALKING_UPSTAIRS'],
       [0.28965416, -0.018843044, -0.15828059, ..., 0.025339478, 30,
        'WALKING_UPSTAIRS'],
       [0.35150347, -0.012423118, -0.20386717, ..., 0.036694843, 30,
        'WALKING_UPSTAIRS']], dtype=object)

In [221]:
data_train.shape

(7352, 563)

## data_train을 X_train과 y_train으로 나누기

**y_train에 6가지 상태(labels)를 저장**

In [299]:
y_train = data_train[:, -1]

In [301]:
y_train

array(['STANDING', 'STANDING', 'STANDING', ..., 'WALKING_UPSTAIRS',
       'WALKING_UPSTAIRS', 'WALKING_UPSTAIRS'], dtype=object)

**X_train에 각 특성의 값들을 저장**

In [302]:
X_train = data_train[:, :-2]

In [296]:
X_train

array([[0.28939527, -0.019337389, -0.053457032, ..., -0.81525768,
        0.19830815, -0.06460045],
       [0.27919461, -0.015663323, -0.10179189, ..., -0.5311951,
        -0.11009805, -0.23601455],
       [0.31754982, -0.01404776, -0.096280712, ..., -0.82728099,
        0.2174813, 0.022021595],
       ...,
       [0.27044966, -0.022394246, -0.10015165, ..., -0.92637066,
        0.13219739, 0.05811329],
       [0.34307286, -0.027223321, -0.0515213, ..., -0.75196373,
        0.24346466, 0.11144337],
       [0.2777796, -0.014836893, -0.10866834, ..., -0.93199321,
        0.10930343, 0.066903197]], dtype=object)

# 순열을 사용한 X_train과 y_train 순서 섞기

In [319]:
random_matrix = np.random.permutation(7352)
X_train, y_train = X_train[random_matrix], y_train[random_matrix]

# GradientBoostingClassifier 사용

In [331]:
from sklearn.ensemble import GradientBoostingClassifier
gbrt = GradientBoostingClassifier(random_state=42)  
gbrt.fit(X_train, y_train)
cross_val_score(gbrt, X_train, y_train, cv=10, scoring="accuracy")

array([0.99048913, 0.99184783, 0.99183673, 0.98503401, 0.99183673,
       0.9877551 , 0.98639456, 0.98503401, 0.99455782, 0.9877551 ])

In [332]:
np.mean([0.99048913, 0.99184783, 0.99183673, 0.98503401, 0.99183673,
       0.9877551 , 0.98639456, 0.98503401, 0.99455782, 0.9877551 ])

0.989254102

# 10-CV Result
## Mean: 0.989254102

## GradientBoostingClassifier 오차행렬 결과

In [333]:
from sklearn.metrics import confusion_matrix
y_train_pred = cross_val_predict(gbrt, X_train, y_train, cv=10)
confusion_matrix(y_train, y_train_pred)

array([[1406,    0,    0,    0,    1,    0],
       [   0, 1249,   36,    0,    0,    1],
       [   0,   30, 1344,    0,    0,    0],
       [   0,    0,    0, 1219,    3,    4],
       [   0,    0,    0,    1,  983,    2],
       [   0,    0,    0,    1,    0, 1072]], dtype=int64)